DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS pots;

CREATE TABLE plants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  plant_name TEXT NOT NULL,
  size TEXT NOT NULL,
  color TEXT NOT NULL
);


CREATE TABLE pots (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  size TEXT NOT NULL,
  color TEXT NOT NULL,
  kind TEXT NOT NULL
);